version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/php:8.0.0-apache-node-browsers
      - image: circleci/mysql:8.0

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mysql:9.4

    environment:
      - APP_DEBUG: true
      - APP_ENV: testing
      - APP_KEY: base64:rphhC6gY6K4axA7khGGs7kFTgDY1t6K1eEn9AaKuNIA=
      - DB_CONNECTION: mysql
      - MYSQL_ALLOW_EMPTY_PASSWORD: true

    working_directory: ~/Sauna-Share

    steps:
      - checkout

      # Install PHP Extension
      - run: sudo docker-php-ext-install pdo_mysql

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "composer.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: composer install -n --prefer-dist

      - save_cache:
          paths:
            - ./vendor
          key: v1-dependencies-{{ checksum "composer.json" }}

      # run seeding
      - run: php artisan migrate

      # run tests!
      - run: php ./vendor/bin/phpunit